AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: code-pipeline-source-bucket-richie
      VersioningConfiguration:
        Status: Enabled